### ISSUE TITLE
Feature request: Add one-line-comment back

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [dinhani/vscode-section-divider#4]
I believe in the previous version of this extension, there's a feature called one-line-comment (or sth. similar) that can add only one line without the manually inputted comment. Now I don't know why it's removed in the current version but is it possible to add it back?

**Comment by dinhani** [comment]
I had removed this functionality because I tought no one used it.

When I needed it, I usually added a normal divider with 3 lines and then fast deleted the two additional lines with Shift+Delete.

Anyway, I restored this functionality with the names `Divider: Add Divider - Level 1 - One Line` and `Divider: Add Divider - Level 2 - One Line`.

It had a default shortcut before, but now I did not assign any default shortcuts to it because I don't see this as the primary functionality of this extension, but you can assign any shortcut you want using VSCode.
