### ISSUE TITLE
End column not observed for tab-indented files

### ISSUE THREAD

**Issue by wleoncio** [dinhani/vscode-section-divider#7]
Running the risk of stirring the pot here, but it seems dividers don't respect the end column when the file is indented with tabs (on version 2.2.1, at least). Here's an example:

![Peek 2020-05-06 07-13](https://user-images.githubusercontent.com/8234768/81140285-26972880-8f69-11ea-8405-3773924e5860.gif)

P.S.: I understand this is unrelated to Issue #1, which was indeed resolved since the divider starts in the correct place. It's just the ending that is not where it should be.

**Comment by dinhani** [comment]
Ok, it is fixed now on version 2.3.1 and already deployed.

The divider will adjust its length at the moment it is created according to the active document tab-width and will appear aligned only for that specific tab-width. 

If the tab-width is changed after a divider is created, it will not appear to be aligned because of the adjustment that happened the moment the divider was created.

**Comment by wleoncio** [comment]
Thank you for handling it so fast, I'm already enjoying 2.3! :)
